# Generated by Django 4.2.25 on 2025-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(help_text='ID do produto', max_length=100)),
                ('product_name', models.CharField(help_text='Nome do produto', max_length=255)),
                ('quantity', models.IntegerField(help_text='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço unitário', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Preço total', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal do pedido', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total do pedido', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Em preparação'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Status do pedido', max_length=50)),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa (ex: pedido_123)', max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Observações do pedido', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Data de confirmação', null=True)),
                ('client', models.ForeignKey(help_text='Cliente do pedido', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cliente.client')),
                ('items', models.ManyToManyField(help_text='Itens do pedido', related_name='orders', to='pedido.orderitem')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
