# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_add_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(
                default=True,
                help_text='Indica se o pedido está ativo. Pedidos sem itens são marcados como inativos.'
            ),
        ),
    ]

