# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_add_active_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('service_id', models.IntegerField(help_text='ID do serviço no Melhor Envio')),
                ('service_name', models.CharField(help_text='Nome do serviço de frete', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do frete', max_digits=10)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço customizado (se aplicável)', max_digits=10, null=True)),
                ('delivery_time', models.IntegerField(help_text='Prazo de entrega em dias')),
                ('custom_delivery_time', models.IntegerField(blank=True, help_text='Prazo customizado (se aplicável)', null=True)),
                ('currency', models.CharField(default='BRL', help_text='Moeda', max_length=3)),
                ('company', models.JSONField(blank=True, help_text='Informações da transportadora', null=True)),
                ('from_postal_code', models.CharField(help_text='CEP de origem', max_length=8)),
                ('to_postal_code', models.CharField(help_text='CEP de destino', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Pedido relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='pedido.order')),
            ],
            options={
                'verbose_name': 'Frete do Pedido',
                'verbose_name_plural': 'Fretes dos Pedidos',
                'db_table': 'order_shipping',
            },
        ),
    ]

