version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    container_name: api-pagamento-frete
    working_dir: /code/src
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    container_name: celery-worker
    working_dir: /code/src
    command: celery -A api_pagamento_frete worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    container_name: celery-beat
    working_dir: /code/src
    command: celery -A api_pagamento_frete beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      celery:
        condition: service_started

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - web
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    command: http web:${PORT} --log=stdout
    ports:
      - "4040:4040" # Painel do Ngrok

volumes:
  postgres_data:
  redis_data:
