# Generated by Django 4.2.7 on 2024-10-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(help_text='Nome do checkout', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor do checkout', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Descrição do checkout', null=True)),
                ('installments', models.IntegerField(default=1, help_text='Número de parcelas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='PENDING', help_text='Status do checkout', max_length=20)),
                ('checkout_url', models.URLField(blank=True, help_text='URL do checkout', null=True)),
                ('success_url', models.URLField(blank=True, help_text='URL de sucesso', null=True)),
                ('failure_url', models.URLField(blank=True, help_text='URL de falha', null=True)),
                ('expires_url', models.URLField(blank=True, help_text='URL de expiração', null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração', null=True)),
                ('client', models.ForeignKey(help_text='Cliente associado ao checkout', on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='cliente.client')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'db_table': 'checkouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
