# Generated by Django 4.2.25 on 2025-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('PAID', 'Pago'), ('RECEIVED', 'Recebido'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('REFUNDING', 'Estornando'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], default='PENDING', help_text='Status do checkout', max_length=50),
        ),
    ]
