# Generated by Django 4.2.25 on 2025-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('asaas_webhook_id', models.CharField(blank=True, help_text='ID do webhook no ASAAS', max_length=50, null=True, unique=True)),
                ('url', models.URLField(help_text='URL do webhook', max_length=500, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email para notificações', max_length=254, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Webhook está habilitado')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('ERROR', 'Erro')], default='ACTIVE', help_text='Status do webhook', max_length=20)),
                ('api_version', models.CharField(default='v3', help_text='Versão da API', max_length=10)),
                ('auth_token', models.CharField(blank=True, help_text='Token de autenticação do webhook', max_length=255, null=True)),
                ('events', models.JSONField(default=list, help_text='Lista de eventos configurados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
