# Generated by Django 4.2.25 on 2025-10-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNotification',
            fields=[
                ('id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='Tipo de evento', max_length=50)),
                ('payment_id', models.CharField(blank=True, help_text='ID do pagamento', max_length=100, null=True)),
                ('subscription_id', models.CharField(blank=True, help_text='ID da assinatura', max_length=100, null=True)),
                ('installment_id', models.CharField(blank=True, help_text='ID da parcela', max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='ID do cliente', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Data do pagamento', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Data de vencimento', null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor', max_digits=10, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor líquido', max_digits=10, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor original', max_digits=10, null=True)),
                ('interest_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de juros', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição', null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa', max_length=100, null=True)),
                ('billing_type', models.CharField(blank=True, help_text='Tipo de cobrança', max_length=50, null=True)),
                ('status', models.CharField(blank=True, help_text='Status', max_length=50, null=True)),
                ('data', models.JSONField(default=dict, help_text='Dados completos da notificação')),
                ('processed', models.BooleanField(default=False, help_text='Notificação foi processada')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Data de processamento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação de Webhook',
                'verbose_name_plural': 'Notificações de Webhook',
                'db_table': 'webhook_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event'], name='webhook_not_event_d3387a_idx'), models.Index(fields=['payment_id'], name='webhook_not_payment_dfea5c_idx'), models.Index(fields=['external_reference'], name='webhook_not_externa_681d0a_idx'), models.Index(fields=['processed'], name='webhook_not_process_ae6f34_idx')],
            },
        ),
    ]
