# Generated by Django 4.2.25 on 2025-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('asaas_id', models.CharField(blank=True, help_text='ID do pagamento no Asaas', max_length=50, null=True, unique=True)),
                ('asaas_checkout_id', models.CharField(blank=True, help_text='ID do checkout no Asaas', max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor do pagamento', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Descrição do pagamento', null=True)),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], help_text='Método de pagamento', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('RECEIVED', 'Recebido'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('REFUNDING', 'Estornando'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], default='PENDING', help_text='Status do pagamento', max_length=50)),
                ('checkout_url', models.URLField(blank=True, help_text='URL do checkout', null=True)),
                ('payment_url', models.URLField(blank=True, help_text='URL de pagamento', null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa', max_length=100, null=True)),
                ('installments', models.IntegerField(default=1, help_text='Número de parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Data do pagamento', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Data do estorno', null=True)),
                ('client', models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cliente.client')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='pagamento.payment')),
            ],
            options={
                'db_table': 'payment_items',
            },
        ),
    ]
