# Generated by Django 4.2.25 on 2025-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Pedido relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pedido.order'),
        ),
    ]
